heat_template_version: 2015-04-30

parameters:
  S_Tmp_name:
    type: string
    label: Service template fq name
    description: Service template for port tuple
  S_Tmp_version:
    type: string
    description: Indicates service version
  S_Tmp_service_mode:
    type: string
    description: service mode
  S_Tmp_service_type:
    type: string
    description: service type
  S_Tmp_image_name:
    type: string
    description: Name of the image
  S_Tmp_flavor:
    type: string
    description: Flavor
  S_Tmp_interface_type_mgmt:
    type: string
    description: service_interface_type for the ServiceTemplate
  S_Tmp_interface_type_left:
    type: string
    description: service_interface_type for the ServiceTemplate
  S_Tmp_interface_type_right:
    type: string
    description: service_interface_type for the ServiceTemplate
  S_Tmp_service_scaling:
    type: string
    description: Indicates whether service scaling is enabled
  svm_name: 
    type: string
    description: Name of the SVM
  S_Ins_name:
    type: string
    label: Service instance fq name
    description: Service instance for port tuple
  management_network:
    type: string
    description: Name of management network to be created
  left_network:
    type: string
    description: Name of left network to be created
  right_network:
    type: string
    description: Name of right network to be created
  NetIPam_ip_prefix_mgmt:
    type: string
    description: subnet prefix for mgmt network
  NetIPam_ip_prefix_len_mgmt:
    type: string
    description: subnet prefix len for mgmt network
  NetIPam_ip_prefix_left:
    type: string
    description: subnet prefix for left network
  NetIPam_ip_prefix_len_left:
    type: string
    description: subnet prefix len for left network
  NetIPam_ip_prefix_right:
    type: string
    description: subnet prefix for right network
  NetIPam_ip_prefix_len_right:
    type: string
    description: subnet prefix len for right network
  domain:
    type: string
    description: Name of the Domain
  NetIPam_ip_prefix_mgmt:
    type: string
    description: subnet prefix for mgmt network
  NetIPam_ip_prefix_len_mgmt:
    type: string
    description: subnet prefix len for mgmt network
  NetIPam_ip_prefix_left:
    type: string
    description: subnet prefix for left network
  NetIPam_ip_prefix_len_left:
    type: string
    description: subnet prefix len for left network
  NetIPam_ip_prefix_right:
    type: string
    description: subnet prefix for right network
  NetIPam_ip_prefix_len_right:
    type: string
    description: subnet prefix len for right network
  NetIPam_ip_prefix_mgmt:
    type: string
    description: subnet prefix for mgmt network
  NetIPam_ip_prefix_len_mgmt:
    type: string
    description: subnet prefix len for mgmt network
  NetIPam_ip_prefix_left:
    type: string
    description: subnet prefix for left network
  NetIPam_ip_prefix_len_left:
    type: string
    description: subnet prefix len for left network
  NetIPam_ip_prefix_right:
    type: string
    description: subnet prefix for right network
  NetIPam_ip_prefix_len_right:
    type: string
    description: subnet prefix len for right network
  NetIPam_addr_from_start_true:
    type: boolean
    description: Address allocation from start of the pool
  port_tuple_name:
    type: string
    description: name of Port Tuple
  flavor:
    type: string
    description: Flavor of the end VMs
  left_vm_image:
    type: string
    description: Name of the left VM image
  right_vm_image:
    type: string
    description: Name of the right VM image
  left_vm_name:
    type: string
    description: Name of the left VM
  right_vm_name:
    type: string
    description: Name of the right VM
  policy_name:
    type: string
    description: Name of the Policy
  policy_fq_name:
    type: string
    description: FQDN of the Policy 
  simple_action:
    type: string
    description: Pass or Deny
  protocol:
    type: string
    description: Protocol
  src_port_end:
    type: number
    description: End of the Source Port Range
  src_port_start:
    type: number
    description: Start of the Source Port Range
  direction:
    type: string
    description: Direction of the Policy
  dst_port_end:
    type: number
    description: End of the Destination Port Range
  dst_port_start:
    type: number
    description: Start of the Destination Port Range
  left_vn_fqdn:
    type: string
    description: FQ Name of the left network
  right_vn_fqdn:
    type: string
    description: FQ Name of the right network
  S_Ins_fq_name:
    type: string
    label: Service instance fq name
    description: Service instance FQDN for port tuple
  route_target:
    type: string
    description: route targets associated with the virtual network
  server_key:
    type: string
    description: Name of key-pair to be used for server instance
  cooldown_initial:
    type: number
    description: Initial wait time; when the first instance is launched.  
  cooldown_scaleup:
    type: number
    description: Wait time interval between scaleup policies.
  cooldown_scaledown: 
    type: number
    description: Wait time interval between scaledown policies.
  period_high: 
    type: number
    description: Interval during which the average cpu load is caluclated before triggering an alarm.
  period_low:
    type: number
    description: Interval during which the average cpu load is caluclated before triggering an alarm.
  threshold_high: 
    type: number
    description: Value of CPU in %; which is compared with, before calling the scaleup policy.
  threshold_low:
    type: number
    description: Value of CPU in %; which is compared with, before calling the scaledown policy.
  meter_name:
    type: string 
    description: Type of meter polled to decide on scaling.


resources:
  mgmt_NetworkIPam:
    type: OS::ContrailV2::NetworkIpam
    properties:
      name: { get_param: management_network }

  left_NetworkIPam:
    type: OS::ContrailV2::NetworkIpam
    properties:
      name: { get_param: left_network }

  right_NetworkIPam:
    type: OS::ContrailV2::NetworkIpam
    properties:
      name: { get_param: right_network }

  mgmt_VirtualNetwork:
    type: OS::ContrailV2::VirtualNetwork
    depends_on: [ mgmt_NetworkIPam ]
    properties:
      name: { get_param: management_network }
      route_target_list:
        {
          route_target_list_route_target: [{ get_param: route_target }],
        }    
      network_ipam_refs: [{ get_resource: mgmt_NetworkIPam }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: { get_param: NetIPam_ip_prefix_mgmt },
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: { get_param: NetIPam_ip_prefix_len_mgmt },
                },
               network_ipam_refs_data_ipam_subnets_addr_from_start: { get_param: NetIPam_addr_from_start_true },
            }]
         }]

  left_VirtualNetwork:
    type: OS::ContrailV2::VirtualNetwork
    depends_on: [ left_NetworkIPam,  NetworkPolicy ] 
    properties:
      name: { get_param: left_network }
      network_ipam_refs: [{ get_resource: left_NetworkIPam }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: { get_param: NetIPam_ip_prefix_left },
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: { get_param: NetIPam_ip_prefix_len_left },
                },
               network_ipam_refs_data_ipam_subnets_addr_from_start: { get_param: NetIPam_addr_from_start_true },
            }]
         }]
      network_policy_refs: [{ get_param: policy_fq_name }]
      network_policy_refs_data:
        [{
          network_policy_refs_data_sequence:
            {
              network_policy_refs_data_sequence_major: 0,
              network_policy_refs_data_sequence_minor: 0,
            },
        }]

  right_VirtualNetwork:
    type: OS::ContrailV2::VirtualNetwork
    depends_on: [ right_NetworkIPam,  NetworkPolicy ]
    properties:
      name: { get_param: right_network }
      network_ipam_refs: [{ get_resource: right_NetworkIPam }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: { get_param: NetIPam_ip_prefix_right },
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: { get_param: NetIPam_ip_prefix_len_right },
                },
               network_ipam_refs_data_ipam_subnets_addr_from_start: { get_param: NetIPam_addr_from_start_true },
            }] 
         }]
      network_policy_refs: [{ get_param: policy_fq_name }]
      network_policy_refs_data:
        [{
          network_policy_refs_data_sequence:
            {
              network_policy_refs_data_sequence_major: 0,
              network_policy_refs_data_sequence_minor: 0,
            },
        }]

  ServiceTemplate:
    type: OS::ContrailV2::ServiceTemplate
    properties:
      name: { get_param: S_Tmp_name }
      service_template_properties:
        {          
          service_template_properties_version: { get_param: S_Tmp_version },
          service_template_properties_service_mode: { get_param: S_Tmp_service_mode },
          service_template_properties_service_type: { get_param: S_Tmp_service_type },
          service_template_properties_image_name: { get_param: S_Tmp_image_name },
          service_template_properties_service_scaling: { get_param: S_Tmp_service_scaling },

          service_template_properties_interface_type:
            [
              {
              service_template_properties_interface_type_service_interface_type: { get_param: S_Tmp_interface_type_mgmt },
              },
              {
              service_template_properties_interface_type_service_interface_type: { get_param: S_Tmp_interface_type_left },
             },
              {
              service_template_properties_interface_type_service_interface_type: { get_param: S_Tmp_interface_type_right },
              }
            ],
          service_template_properties_flavor: { get_param: S_Tmp_flavor },
          service_template_properties_service_virtualization_type: virtual-machine ,
        }
      domain: { get_param: domain }

  ServiceInstance:
    type: OS::ContrailV2::ServiceInstance
    depends_on: [ ServiceTemplate ]
    properties:
      name: { get_param: S_Ins_name }
      service_instance_properties:
        {
          service_instance_properties_interface_list:
            [
              {
                service_instance_properties_interface_list_virtual_network:
                 {
                   list_join: [':', { get_attr: [mgmt_VirtualNetwork, fq_name ] } ]
                 },
              },
              {
              service_instance_properties_interface_list_virtual_network:
                {
                   list_join: [':', { get_attr: [ left_VirtualNetwork, fq_name ] } ]
                },
              },
              {
              service_instance_properties_interface_list_virtual_network:
                {
                   list_join: [':', { get_attr: [ right_VirtualNetwork, fq_name ] } ]
                },
              }
            ],
        }
      service_template_refs: [{ get_resource: ServiceTemplate }]
  Instance_Group:
    type: OS::Heat::AutoScalingGroup
    properties:
      cooldown: { get_param: cooldown_initial }
      desired_capacity: 1
      max_size: 5
      min_size: 1
      resource:
        type: service_instance.yaml
        properties:
          image: { get_param: S_Tmp_image_name }
          flavor: { get_param: S_Tmp_flavor }
          virtual_network_M: { get_param: management_network }
          virtual_network_M_fqdn: { list_join: [':', { get_attr: [mgmt_VirtualNetwork, fq_name ] } ] }
          virtual_network_L: { get_param: left_network }
          virtual_network_L_fqdn: { list_join: [':', { get_attr: [ left_VirtualNetwork, fq_name ] } ] }
          virtual_network_R: { get_param: right_network }
          virtual_network_R_fqdn: { list_join: [':', { get_attr: [ right_VirtualNetwork, fq_name ] } ] }
          service_instance_name: { list_join: [':', { get_attr: [ ServiceInstance, fq_name ] } ] }
          service_interface_type_M: 'management'
          service_interface_type_L: 'left'
          service_interface_type_R: 'right'
          port_tuple_name: port_tuple_name

  scaleup_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: Instance_Group }
      cooldown: { get_param: cooldown_scaleup }
      scaling_adjustment: 1

  high_alarm:
    type: OS::Ceilometer::Alarm
    properties:
      description: Alarm-trigger when threshold high
      meter_name: { get_param: meter_name} 
      statistic: avg
      period: { get_param: period_high }
      evaluation_periods: 1
      threshold: { get_param: threshold_high }
      alarm_actions:
        - {get_attr: [scaleup_policy, alarm_url]}
      comparison_operator: ge

  scaledown_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: Instance_Group }
      cooldown: { get_param: cooldown_scaledown }
      scaling_adjustment: -1 
      
  low_alarm:
    type: OS::Ceilometer::Alarm
    properties:
      meter_name: { get_param: meter_name}
      description: Alarm-trigger when threshold low
      statistic: avg
      period: { get_param: period_low }
      evaluation_periods: 1
      threshold: { get_param: threshold_low }
      alarm_actions:
        - {get_attr: [scaledown_policy, alarm_url]}
      comparison_operator: le

  left_VM_InstanceIp:
    type: OS::ContrailV2::InstanceIp
    depends_on: [  left_VM_VirtualMachineInterface, left_VirtualNetwork ]
    properties:
      virtual_machine_interface_refs: [{ get_resource:  left_VM_VirtualMachineInterface }]
      virtual_network_refs: [{ list_join: [':', { get_attr: [ left_VirtualNetwork, fq_name ] } ] }]

  right_VM_InstanceIp:
    type: OS::ContrailV2::InstanceIp
    depends_on: [ right_VM_VirtualMachineInterface, right_VirtualNetwork ]
    properties:
      virtual_machine_interface_refs: [{ get_resource: right_VM_VirtualMachineInterface }]
      virtual_network_refs: [{ list_join: [':', { get_attr: [ right_VirtualNetwork, fq_name ] } ] }]
      
      
  left_VM_VirtualMachineInterface:
    type: OS::ContrailV2::VirtualMachineInterface
    properties:
      name: { get_param: left_vm_name }
      virtual_network_refs: [{ list_join: [':', { get_attr: [ left_VirtualNetwork, fq_name ] } ] }]
      
  
  right_VM_VirtualMachineInterface:
    type: OS::ContrailV2::VirtualMachineInterface
    properties:
      name: { get_param: right_vm_name }
      virtual_network_refs: [{ list_join: [':', { get_attr: [ right_VirtualNetwork, fq_name ] } ] }]
      
  
  left_VM:
    type: OS::Nova::Server
    depends_on: [ left_VM_InstanceIp ]
    properties:
      name: {get_param: left_vm_name }
      image: { get_param:  left_vm_image }
      key_name: { get_param: server_key }
      flavor: { get_param: flavor }
      networks:
        - port: { get_resource:  left_VM_VirtualMachineInterface }
       

  right_VM:
    type: OS::Nova::Server
    depends_on: [ right_VM_InstanceIp  ]
    properties:
      name: {get_param: right_vm_name }
      image: { get_param:  right_vm_image }
      key_name: { get_param: server_key }
      flavor: { get_param: flavor }
      networks:
        - port: { get_resource: right_VM_VirtualMachineInterface }
  
  NetworkPolicy:
    type: OS::ContrailV2::NetworkPolicy
    properties:
      name: { get_param: policy_name }
      network_policy_entries: { network_policy_entries_policy_rule: [{ 
		network_policy_entries_policy_rule_direction: { get_param: direction },
		network_policy_entries_policy_rule_protocol: { get_param: protocol },
		network_policy_entries_policy_rule_src_ports: [{
			network_policy_entries_policy_rule_src_ports_start_port: { get_param: src_port_start },
			network_policy_entries_policy_rule_src_ports_end_port: { get_param: src_port_end }
								}],
 		network_policy_entries_policy_rule_dst_ports: [{
			network_policy_entries_policy_rule_dst_ports_start_port: { get_param: dst_port_start },
			network_policy_entries_policy_rule_dst_ports_end_port: { get_param: dst_port_end }
								}],
		network_policy_entries_policy_rule_dst_addresses: [{
			network_policy_entries_policy_rule_dst_addresses_virtual_network: { get_param: right_vn_fqdn }
								}],
		network_policy_entries_policy_rule_src_addresses: [{
			network_policy_entries_policy_rule_src_addresses_virtual_network: { get_param: left_vn_fqdn }
								}],
		network_policy_entries_policy_rule_action_list: { 
			network_policy_entries_policy_rule_action_list_simple_action: { get_param: simple_action },
			network_policy_entries_policy_rule_action_list_apply_service: 
									[{ get_param: S_Ins_fq_name }]
								},
									}]
	}



 

